### PR TITLE
New update

### PR DESCRIPTION
**Pull request by banji1**
Pls help me merge this new PR

### CODE REVIEW

**Comment by bidex160** [comment]
it has conflit with the master fork the repo again the clone

**Comment by banji1** [comment]
ls how do i delete the fork i have so that i'd fork a new one?

**Comment by bidex160** [comment]
Go to the repo on ur account then setting scrol down u will see danger zone

**Comment by banji1** [comment]
Issues resolve



Kindly help me merge PR # 484.

**Pull request closed without merging**
