### PR TITLE
Corrected the name

### PR DESCRIPTION
**Pull request by Deifa**

### CODE REVIEW

**Comment by LifeofDan-EL** [comment]
Hope there's no other script by you though?

**Comment by Deifa** [comment]
> Hope there's no other script by you though?

there is Godson_Imiebo.js had to change the name

**Comment by Deifa** [comment]
@LifeofDan-EL should i find a way to delete it? or i should delete and pull request again?

**Comment by LifeofDan-EL** [comment]
Chill, work on the cloned repo that has the initial one, commit and create the PR frit. No need to create a new file completely to avoid multiple scripts.

**Pull request merged**
