### PR TITLE
Added my script to scripts folder

### PR DESCRIPTION
**Pull request by simeon4real**
Added my script file correctly to the `scripts` folder.

### CODE REVIEW

**Comment by Tobi-Osimosu** [comment]
change This to this. Please follow the correct naming convention

**Comment by simeon4real** [comment]
Alright @TabithaKavyu ,  sending another pr in a bit.  Thanks for the heads up.

**Comment by TabithaKavyu** [comment]
@simeon4real I think you mentioned the wrong person

**Comment by simeon4real** [comment]
> @simeon4real I think you mentioned the wrong person

Hey @TabithaKavyu, I'm sorry. My bad.

**Pull request merged**
