### PR TITLE
Urchylis hng project

### PR DESCRIPTION
**Pull request by ucheuzor**
my team incredible project using javascript

### CODE REVIEW

**Comment by LifeofDan-EL** [comment]
Work on only your script file.

**Comment by bidex160** [comment]
U are pushing two files here

**Comment by ucheuzor** [comment]
What is wrong with that I ignored the log file using git ignore and you
rejected it. My laptop battery is down. I can't do anything now. Till
tomorrow

**Comment by LifeofDan-EL** [comment]
Sorry, no vex.

**Pull request merged**
