### PR TITLE
Email address corrected

### PR DESCRIPTION
**Pull request by kelrob**

### CODE REVIEW

**Comment by kelrob** [comment]
Email Address corrected

**Comment by elishaukpong** [comment]
Why are you deleting index.php?

**Comment by kelrob** [comment]
Trying to avoid conflict

**Comment by LifeofDan-EL** [comment]
Close the PR, add just your script to the folder then commit. Don't tamper with any other thing.

**Comment by Sproff** [comment]
Can’t be merged 
Conflicting files please resolve

**Pull request closed without merging**
